# Generated by Django 3.1.7 on 2021-03-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_column='Name', max_length=200),
        ),
    ]
