# Generated by Django 3.1.7 on 2021-03-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0005_auto_20210317_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='mission_stmt',
            new_name='mission',
        ),
    ]
