# Generated by Django 3.1.7 on 2021-03-20 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0010_auto_20210320_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='ein',
            field=models.IntegerField(db_column='EIN'),
        ),
    ]
