# Generated by Django 3.1.7 on 2021-04-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='facebook',
            field=models.CharField(blank=True, db_column='Facebook', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, db_column='Twitter', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, db_column='Website', max_length=200, null=True),
        ),
    ]
