# Generated by Django 3.1.7 on 2021-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0007_auto_20210416_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=45, null=True),
        ),
    ]
