# Generated by Django 3.1.7 on 2021-04-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0008_auto_20210416_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.CharField(blank=True, db_column='Channel', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, db_column='User', max_length=50),
        ),
    ]
