# Generated by Django 3.1.7 on 2021-03-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0003_changemaker_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='changemaker',
            table='Changemaker',
        ),
    ]
