# Generated by Django 3.1.7 on 2021-02-25 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('rid', models.IntegerField(db_column='RID', primary_key=True, serialize=False)),
                ('regionname', models.CharField(db_column='RegionName', max_length=25)),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ein', models.IntegerField(db_column='EIN', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('address1', models.CharField(db_column='Address1', max_length=50)),
                ('address2', models.CharField(db_column='Address2', max_length=25)),
                ('city', models.CharField(db_column='City', max_length=25)),
                ('state', models.CharField(db_column='State', max_length=2)),
                ('zip', models.IntegerField(db_column='Zip')),
                ('country', models.CharField(db_column='Country', max_length=3)),
                ('phone', models.CharField(db_column='Phone', max_length=14)),
                ('missionstmt', models.TextField(db_column='MissionStmt')),
                ('website', models.CharField(db_column='Website', max_length=25)),
                ('causes', models.TextField(db_column='Causes')),
                ('regionid', models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.DO_NOTHING, to='collaboratory_api.region')),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Changemaker',
            fields=[
                ('cid', models.IntegerField(db_column='CID', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='Fname', max_length=25)),
                ('lname', models.CharField(db_column='Lname', max_length=25)),
                ('orgein', models.ForeignKey(db_column='OrgEIN', on_delete=django.db.models.deletion.DO_NOTHING, to='collaboratory_api.organization')),
                ('regionid', models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.DO_NOTHING, to='collaboratory_api.region')),
            ],
            options={
                'db_table': 'Changemaker',
            },
        ),
    ]
