# Generated by Django 3.1.7 on 2021-03-02 09:43

from django.db import migrations

def create_data(apps, schema_editor):
    Role = apps.get_model('collaboratory_api', 'Role')
    test_role = Role.objects.get(role_id=2)
    Organization = apps.get_model('collaboratory_api', 'Organization')
    test_org = Organization.objects.get(ein=810830144)

    User = apps.get_model('collaboratory_api', 'User')
    User(user_id=1, username="changeymcc", first_name="Changey", last_name="McChangemaker", phone="000-000-0000", preferred_pronouns="he/him", role_id=test_role, organization_id=test_org).save()


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0002_create_role_data'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
