# Generated by Django 3.1.7 on 2021-03-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cause_id',
            field=models.ManyToManyField(to='collaboratory_api.Cause'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='region_id',
            field=models.ManyToManyField(to='collaboratory_api.Region'),
        ),
    ]
