# Generated by Django 3.1.7 on 2021-04-12 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaboratory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboratory_api.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel_id',
            field=models.ForeignKey(db_column='ChannelID', null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboratory_api.channel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(db_column='PostID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboratory_api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
