# Generated by Django 3.1.7 on 2021-04-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0002_event_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]