# Generated by Django 3.1.7 on 2021-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0002_auto_20210317_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=45),
        ),
    ]
