# Generated by Django 3.1.7 on 2021-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0002_create_changemaker_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemaker',
            name='email',
            field=models.CharField(db_column='Email', default='email@domain.com', max_length=50),
        ),
    ]
