# Generated by Django 3.1.7 on 2021-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0002_auto_20210320_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address2',
            field=models.CharField(blank=True, db_column='Address2', max_length=50, null=True),
        ),
    ]
