# Generated by Django 3.1.7 on 2021-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0003_changemaker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(db_column='UID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=25)),
                ('lastname', models.CharField(db_column='LastName', max_length=25)),
                ('preferredpronouns', models.CharField(db_column='pronouns', max_length=10)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
