# Generated by Django 3.1.7 on 2021-04-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0003_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.IntegerField(db_column='AnnouncementID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=50)),
                ('text', models.TextField(db_column='Text')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='Date')),
                ('event_id', models.ForeignKey(blank=True, db_column='EventID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboratory_api.event')),
                ('user_id', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collaboratory_api.user')),
            ],
            options={
                'db_table': 'Announcement',
            },
        ),
    ]