# Generated by Django 3.1.7 on 2021-03-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0003_auto_20210320_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ein',
            field=models.IntegerField(blank=True, db_column='EIN', null=True),
        ),
    ]
