# Generated by Django 3.1.7 on 2021-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0003_auto_20210317_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='zip',
            field=models.CharField(blank=True, db_column='Zip', max_length=20, null=True),
        ),
    ]
