# Generated by Django 3.1.7 on 2021-03-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0004_auto_20210317_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mission_stmt',
            field=models.CharField(max_length=255),
        ),
    ]
