# Generated by Django 3.1.7 on 2021-03-02 09:43

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('collaboratory_api', 'User')
    User(uid=1, firstname="Changey", lastname="McChangemaker", preferredpronouns="he/him").save()


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0004_user'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
