# Generated by Django 3.1.7 on 2021-04-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0004_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
    ]
