# Generated by Django 3.1.7 on 2021-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0005_create_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='Password', default='1234', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferredpronouns',
            field=models.CharField(db_column='Pronouns', max_length=10),
        ),
    ]
