# Generated by Django 3.1.7 on 2021-03-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0006_auto_20210317_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.TextField(db_column='MissionStmt'),
        ),
    ]
