# Generated by Django 3.1.7 on 2021-04-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0006_event_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user_id',
        ),
        migrations.AddField(
            model_name='event',
            name='RSVP',
            field=models.CharField(blank=True, db_column='RSVP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(blank=True, db_column='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, db_column='Text'),
        ),
    ]
