# Generated by Django 3.1.7 on 2021-03-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0007_auto_20210317_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(db_column='EventID', primary_key=True, serialize=False),
        ),
    ]
