# Generated by Django 3.1.7 on 2021-04-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0008_auto_20210416_0007'),
        ('collaboratory_api', '0009_auto_20210416_1843'),
    ]

    operations = [
    ]
