# Generated by Django 3.1.7 on 2021-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0010_merge_20210417_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(db_column='PostID', primary_key=True, serialize=False),
        ),
    ]
