# Generated by Django 3.1.7 on 2021-04-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0012_auto_20210417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='facebook',
            field=models.CharField(blank=True, db_column='Facebook', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, db_column='Twitter', max_length=200, null=True),
        ),
    ]
