# Generated by Django 3.1.7 on 2021-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0013_auto_20210418_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=45, null=True),
        ),
    ]
