# Generated by Django 3.1.7 on 2021-04-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_api', '0014_auto_20210418_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, db_column='Website', max_length=200, null=True),
        ),
    ]
